Replace syn with handwritten TokenStream parser/output
lifthrasiir/hexf pull request #29
Opened 2024-12-14 11:23 UTC by ajtribick

Since syn is somewhat infamous as a rather heavy crate in the build process, and the input/output of these macros are not too complex, here's a manual implementation.

- The implementation does NOT support escape sequences in string literals, which are of questionable utility here, but this is technically a breaking change.
- I've left in raw string literal support since this was included in the test cases already.

2025-04-22 08:30 UTC, youknowone commented
@lifthrasiir Could you review this PR? I feel like this is out of my review coverage

2025-04-22 09:12 UTC, lifthrasiir requested changes
I'm good with removing `syn` dependency. That said, I'm not very sure if this handles or at least recognizes some more legitimate edge cases like these:

```rust
hexf32!(    "0x0.0p0"     )
hexf32!(
    "0x0.00000000000000000000000000000000000000000000000000000000000p0"
) // can actually occur with rustfmt
```

I personally like to handle these two cases and reject any other edge cases, but I'll leave it up to you because these cases should be very rare anyway. The point is that if we don't support a particular syntax we should report why so that the user can rewrite it into the supported syntax.

2025-04-22 09:12 UTC, lifthrasiir commented on src/lib.rs
> +    let mut tokens = TokenStream::new();
Please note the intended code as a comment.

```suggestion
    // ::core::compile_error!{<message_token>}
    let mut tokens = TokenStream::new();
```

2025-04-22 09:12 UTC, lifthrasiir commented on src/lib.rs
> +    }
I think `span` is the only known span in this context, so a closure seems a better fit here.

2025-04-22 09:12 UTC, lifthrasiir commented on src/lib.rs
> +            // usage of these macros, they would be of questionable utility.
I agree we shouldn't handle them here, but I think we should clearly indicate that escape sequences are explicitly not supported. I'm okay to reject the string if its code contains `\`. The same comment applies to the other branch.

2025-04-22 09:12 UTC, lifthrasiir commented on src/lib.rs
> +
I would prefer to split the rest of this patch into a separate file, since a nitty-gritty of dealing with `TokenStream` shouldn't be the main concern here.

(I even feel that this parsing code has a bigger utility for other libraries and can be made into a small individual crate! If you feel like so and update this PR accordingly I will accept that too.)

2025-06-05 19:41 UTC, ajtribick commented on src/lib.rs
> +            // usage of these macros, they would be of questionable utility.
Added a specific error message when escape sequences are detected.

2025-06-05 19:44 UTC, ajtribick commented on src/lib.rs
> +
Moved to a separate file. I think there definitely is some utility to have a library that handles proc-macros which consist of a single string, on the other hand there is also some value in minimizing the dependencies of a crate like this. Might revisit this in the future if I end up putting in functionality like this in my own crate, for which a compile-time literal parser might also be useful (though I need to get round to writing proper parsing functionality at some point...).

2025-06-05 19:45 UTC, ajtribick commented
Added some tests with whitespace, and addressed the other points.

2025-09-02 01:17 UTC, merged

2025-09-02 01:17 UTC, lifthrasiir commented
Thank you, and sorry for the late merger (I completely forgot to review the new commit for months until youknowone reminded me)!